package utils

const (
	NOTIF_EMAIL_VERIFICATION        = "email_verification"
	NOTIF_EMAIL_FORGOT_PASSWORD     = "reset_password"
	NOTIF_EMAIL_CREATE_CUSTOMER     = "create_customer"
	NOTIF_EMAIL_UPDATE_CUSTOMER     = "update_customer"
	NOTIF_EMAIL_UPDATE_ORDER_STATUS = "email_update_order_status"
	NOTIF_PUSH                      = "notif_push"
)

const (
	//client error
	SESSION_EXPIRED           = "401: SESSION_EXPIRED"
	TOKEN_INVALID             = "401: TOKEN_INVALID"
	TOKEN_EXPIRED             = "401: TOKEN_EXPIRED"
	LOGIN_INVALID             = "401: LOGIN_INVALID"
	ACCESS_FORBIDDEN          = "403: ACCESS_FORBIDDEN"
	DATA_NOT_FOUND            = "404: DATA_NOT_FOUND"
	EMAIL_ALREADY_EXISTS      = "409: EMAIL_ALREADY_EXISTS"
	EMAIL_NOT_VERIFIED        = "409: EMAIL_NOT_VERIFIED"
	DATA_ALREADY_EXISTS       = "409: DATA_ALREADY_EXISTS"
	DATA_STILL_IN_USED        = "409: DATA_STILL_IN_USED"
	INVALID_STATUS_TRANSITION = "409: INVALID_STATUS_TRANSITION"
	INVALID_PAYMENT_METHOD    = "422: INVALID_PAYMENT_METHOD"
	INVALID_NOTIFICATION_TYPE = "422: INVALID_NOTIFICATION_TYPE"
	INVALID_ID                = "422: INVALID_ID"

	// server error
	INTERNAL_SERVER_ERROR  = "500: INTERNAL_SERVER_ERROR"
	SERVICE_UNAVAILABLE    = "503: SERVICE_UNAVAILABLE"
	TIMEOUT_LIMIT_EXCEEDED = "504: TIMEOUT_LIMIT_EXCEEDED"
)
