services:
  nginx:
    container_name: nginx
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      ui:
        condition: service_started
      api-gateway-service:
        condition: service_started
    networks:
      - api-gateway-net

  user-db:
    container_name: user-db
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: user-service
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - postgres_user_data:/var/lib/postgresql
    networks:
      - user-db-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  user-service:
    container_name: user-service
    build:
      context: ./api/user-service
      dockerfile: Dockerfile
    env_file:
      - ./api/user-service/.env
    restart: unless-stopped
    depends_on:
      user-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    networks:
      - user-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net
      - api-gateway-net

  user-publisher-worker:
    container_name: user-publisher-worker
    build:
      context: ./api/user-service
      dockerfile: Dockerfile
    env_file:
      - ./api/user-service/.env
    command: ["./app", "publisher-worker"]
    restart: unless-stopped
    depends_on:
      user-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    networks:
      - user-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net

  product-db:
    container_name: product-db
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: product-service
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - postgres_product_data:/var/lib/postgresql
    networks:
      - product-db-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  product-service:
    container_name: product-service
    build:
      context: ./api/product-service
      dockerfile: Dockerfile
    env_file:
      - ./api/product-service/.env
    restart: unless-stopped
    depends_on:
      product-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    networks:
      - product-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net
      - api-gateway-net

  product-publisher-worker:
    container_name: product-publisher-worker
    build:
      context: ./api/product-service
      dockerfile: Dockerfile
    env_file:
      - ./api/product-service/.env
    command: ["./app", "publisher-worker"]
    restart: unless-stopped
    depends_on:
      product-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    networks:
      - product-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net

  product-consumer-worker:
    container_name: product-consumer-worker
    build:
      context: ./api/product-service
      dockerfile: Dockerfile
    env_file:
      - ./api/product-service/.env
    command: ["./app", "consumer-worker"]
    restart: unless-stopped
    depends_on:
      product-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    networks:
      - product-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net

  order-db:
    container_name: order-db
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: order-service
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - postgres_order_data:/var/lib/postgresql
    networks:
      - order-db-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  order-service:
    container_name: order-service
    build:
      context: ./api/order-service
      dockerfile: Dockerfile
    env_file:
      - ./api/order-service/.env
    restart: unless-stopped
    depends_on:
      order-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      elasticsearch:
        condition: service_healthy
      user-service:
        condition: service_started
      product-service:
        condition: service_started
    networks:
      - order-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net
      - api-gateway-net

  order-publisher-worker:
    container_name: order-publisher-worker
    build:
      context: ./api/order-service
      dockerfile: Dockerfile
    env_file:
      - ./api/order-service/.env
    command: ["./app", "publisher-worker"]
    restart: unless-stopped
    depends_on:
      order-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      elasticsearch:
        condition: service_healthy
      user-service:
        condition: service_started
      product-service:
        condition: service_started
    networks:
      - order-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net

  order-consumer-worker:
    container_name: order-consumer-worker
    build:
      context: ./api/order-service
      dockerfile: Dockerfile
    env_file:
      - ./api/order-service/.env
    command: ["./app", "consumer-worker"]
    restart: unless-stopped
    depends_on:
      order-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      elasticsearch:
        condition: service_healthy
      user-service:
        condition: service_started
      product-service:
        condition: service_started
    networks:
      - order-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net

  payment-db:
    container_name: payment-db
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: payment-service
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - postgres_payment_data:/var/lib/postgresql
    networks:
      - payment-db-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  payment-service:
    container_name: payment-service
    build:
      context: ./api/payment-service
      dockerfile: Dockerfile
    env_file:
      - ./api/payment-service/.env
    restart: unless-stopped
    depends_on:
      payment-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      elasticsearch:
        condition: service_healthy
      user-service:
        condition: service_started
      product-service:
        condition: service_started
      order-service:
        condition: service_started
    networks:
      - payment-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net
      - api-gateway-net

  payment-publisher-worker:
    container_name: payment-publisher-worker
    build:
      context: ./api/payment-service
      dockerfile: Dockerfile
    env_file:
      - ./api/payment-service/.env
    command: ["./app", "publisher-worker"]
    restart: unless-stopped
    depends_on:
      payment-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      elasticsearch:
        condition: service_healthy
      user-service:
        condition: service_started
      product-service:
        condition: service_started
      order-service:
        condition: service_started
    networks:
      - payment-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net

  payment-consumer-worker:
    container_name: payment-consumer-worker
    build:
      context: ./api/payment-service
      dockerfile: Dockerfile
    env_file:
      - ./api/payment-service/.env
    command: ["./app", "consumer-worker"]
    restart: unless-stopped
    depends_on:
      payment-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      elasticsearch:
        condition: service_healthy
      user-service:
        condition: service_started
      product-service:
        condition: service_started
      order-service:
        condition: service_started
    networks:
      - payment-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net

  notification-db:
    container_name: notification-db
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: notification-service
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - postgres_notification_data:/var/lib/postgresql
    networks:
      - notification-db-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  notification-service:
    container_name: notification-service
    build:
      context: ./api/notification-service
      dockerfile: Dockerfile
    env_file:
      - ./api/notification-service/.env
    restart: unless-stopped
    depends_on:
      notification-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    networks:
      - notification-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net
      - api-gateway-net

  notification-consumer-worker:
    container_name: notification-consumer-worker
    build:
      context: ./api/notification-service
      dockerfile: Dockerfile
    env_file:
      - ./api/notification-service/.env
    command: ["./app", "consumer-worker"]
    restart: unless-stopped
    depends_on:
      notification-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    networks:
      - notification-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net

  api-gateway-service:
    container_name: api-gateway-service
    build:
      context: ./api/api-gateway
      dockerfile: Dockerfile
    env_file:
      - ./api/api-gateway/.env
    restart: unless-stopped
    depends_on:
      user-service:
        condition: service_started
      product-service:
        condition: service_started
      order-service:
        condition: service_started
      payment-service:
        condition: service_started
      notification-service:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - redis-net
      - api-gateway-net

  ui:
    container_name: ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    env_file:
      - ./ui/.env
    restart: unless-stopped
    depends_on:
      api-gateway-service:
        condition: service_started
    networks:
      - api-gateway-net

  redis:
    container_name: redis
    image: redis:8.4
    restart: unless-stopped
    networks:
      - redis-net
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RBMQ_USER}
      RABBITMQ_DEFAULT_PASSWORD: ${RBMQ_PASS}
    networks:
      - rabbitmq-net
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 40s

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: unless-stopped
    networks:
      - elasticsearch-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl -s http://localhost:9200/_cluster/health | grep -vq ''"status":"red"''',
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

volumes:
  postgres_user_data:
  postgres_product_data:
  postgres_order_data:
  postgres_payment_data:
  postgres_notification_data:

networks:
  user-db-net:
  product-db-net:
  order-db-net:
  payment-db-net:
  notification-db-net:
  redis-net:
  rabbitmq-net:
  elasticsearch-net:
  api-gateway-net:
