package utils

const (
	NOTIF_EMAIL_VERIFICATION    = "email_verification"
	NOTIF_EMAIL_FORGOT_PASSWORD = "reset_password"
	NOTIF_EMAIL_CREATE_CUSTOMER = "create_customer"
	NOTIF_EMAIL_UPDATE_CUSTOMER = "update_customer"
	NOTIF_PUSH                  = "notif_push"
)

const (
	//client error
	LAT_OR_LNG_REQUIRED       = "400: LATITUDE_OR_LONGITUDE_REQUIRED"
	SESSION_EXPIRED           = "401: SESSION_EXPIRED"
	TOKEN_INVALID             = "401: TOKEN_INVALID"
	TOKEN_EXPIRED             = "401: TOKEN_EXPIRED"
	LOGIN_INVALID             = "401: LOGIN_INVALID"
	ACCESS_FORBIDDEN          = "403: ACCESS_FORBIDDEN"
	DATA_NOT_FOUND            = "404: DATA_NOT_FOUND"
	EMAIL_ALREADY_EXISTS      = "409: EMAIL_ALREADY_EXISTS"
	EMAIL_NOT_VERIFIED        = "409: EMAIL_NOT_VERIFIED"
	DATA_ALREADY_EXISTS       = "409: DATA_ALREADY_EXISTS"
	DATA_STILL_IN_USED        = "409: DATA_STILL_IN_USED"
	INVALID_STATUS_TRANSITION = "409: INVALID_STATUS_TRANSITION"
	RELATION_DATA_NOT_FOUND   = "422: RELATION_DATA_NOT_FOUND"
	LAT_OR_LNG_INVALID        = "422: LATITUDE_OR_LONGITUDE_INVALID"
	DISTANCE_TOO_FAR          = "422: DISTANCE_TOO_FAR"
	ORDER_CODE_INVALID        = "422: ORDER_CODE_INVALID"
	ID_INVALID                = "422: ID_INVALID"

	// server error
	INTERNAL_SERVER_ERROR  = "500: INTERNAL_SERVER_ERROR"
	SERVICE_UNAVAILABLE    = "503: SERVICE_UNAVAILABLE"
	TIMEOUT_LIMIT_EXCEEDED = "504: TIMEOUT_LIMIT_EXCEEDED"
)
