services:
  user-db:
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: user-service
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - postgres_user_data:/var/lib/postgresql
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - user-db-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  user-service:
    build: 
      context: ./user-service
      dockerfile: Dockerfile
    env_file:
      - ./user-service/.env
    ports:
      - "8080:8080"
    command: ["./app", "start"]
    restart: unless-stopped
    depends_on:
      user-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - user-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net
      - api-gateway-net
  
  user-publisher-worker:
    build: 
      context: ./user-service
      dockerfile: Dockerfile
    env_file:
      - ./user-service/.env
    command: ["./app", "publisher-worker"]
    restart: unless-stopped
    depends_on:
      user-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - user-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net

  product-db:
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: product-service
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - postgres_product_data:/var/lib/postgresql
    ports:
      - "127.0.0.1:5433:5432"
    networks:
      - product-db-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  product-service:
    build: 
      context: ./product-service
      dockerfile: Dockerfile
    env_file:
      - ./product-service/.env
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      product-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - product-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net
      - api-gateway-net

  product-publisher-worker:
    build: 
      context: ./product-service
      dockerfile: Dockerfile
    env_file:
      - ./product-service/.env
    command: ["./app", "publisher-worker"]
    restart: unless-stopped
    depends_on:
      product-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - product-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net

  product-consumer-worker:
    build: 
      context: ./product-service
      dockerfile: Dockerfile
    env_file:
      - ./product-service/.env
    command: ["./app", "consumer-worker"]
    restart: unless-stopped
    depends_on:
      product-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - product-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net

  order-db:
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: order-service
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - postgres_order_data:/var/lib/postgresql
    ports:
      - "127.0.0.1:5434:5432"
    networks:
      - order-db-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
  
  order-service:
    build: 
      context: ./order-service
      dockerfile: Dockerfile
    env_file:
      - ./order-service/.env
    ports:
      - "8082:8082"
    restart: unless-stopped
    depends_on:
      order-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      user-service:
        condition: service_started
      product-service:
        condition: service_started
    networks:
      - order-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net
      - api-gateway-net

  order-publisher-worker:
    build: 
      context: ./order-service
      dockerfile: Dockerfile
    env_file:
      - ./order-service/.env
    command: ["./app", "publisher-worker"]
    restart: unless-stopped
    depends_on:
      order-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      user-service:
        condition: service_started
      product-service:
        condition: service_started
    networks:
      - order-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net

  order-consumer-worker:
    build: 
      context: ./order-service
      dockerfile: Dockerfile
    env_file:
      - ./order-service/.env
    command: ["./app", "consumer-worker"]
    restart: unless-stopped
    depends_on:
      order-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      user-service:
        condition: service_started
      product-service:
        condition: service_started
    networks:
      - order-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net

  payment-db:
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: payment-service
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - postgres_payment_data:/var/lib/postgresql
    ports:
      - "127.0.0.1:5435:5432"
    networks:
      - payment-db-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  payment-service:
    build: 
      context: ./payment-service
      dockerfile: Dockerfile
    env_file:
      - ./payment-service/.env
    ports:
      - "8083:8083"
    restart: unless-stopped
    depends_on:
      payment-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      user-service:
        condition: service_started
      product-service:
        condition: service_started
      order-service:
        condition: service_started
    networks:
      - payment-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net
      - api-gateway-net
  
  payment-publisher-worker:
    build: 
      context: ./payment-service
      dockerfile: Dockerfile
    env_file:
      - ./payment-service/.env
    command: ["./app", "publisher-worker"]
    restart: unless-stopped
    depends_on:
      payment-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      user-service:
        condition: service_started
      product-service:
        condition: service_started
      order-service:
        condition: service_started
    networks:
      - payment-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net

  notification-db:
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: notification-service
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - postgres_notification_data:/var/lib/postgresql
    ports:
      - "127.0.0.1:5436:5432"
    networks:
      - notification-db-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  notification-service:
    build: 
      context: ./notification-service
      dockerfile: Dockerfile
    env_file:
      - ./notification-service/.env
    ports:
      - "8084:8084"
    restart: unless-stopped
    depends_on:
      notification-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - notification-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net
      - api-gateway-net
  
  notification-consumer-worker:
    build: 
      context: ./notification-service
      dockerfile: Dockerfile
    env_file:
      - ./notification-service/.env
    command: ["./app", "consumer-worker"]
    restart: unless-stopped
    depends_on:
      notification-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - notification-db-net
      - redis-net
      - rabbitmq-net
      - elasticsearch-net

  api-gateway-service:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    env_file:
      - ./notification-service/.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      user-service:
        condition: service_started
      product-service:
        condition: service_started
      order-service:
        condition: service_started
      payment-service:
        condition: service_started
      notification-service:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - redis-net
      - api-gateway-net

  redis:
    image: redis:8.4
    restart: unless-stopped
    ports:
    - "127.0.0.1:6379:6379"
    networks:
    - redis-net
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RBMQ_USER}
      RABBITMQ_DEFAULT_PASSWORD: ${RBMQ_PASS}
    networks:
      - rabbitmq-net
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
  
  elasticsearch:
    image: elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    restart: unless-stopped
    networks:
      - elasticsearch-net
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

volumes:
  postgres_user_data:
  postgres_product_data:
  postgres_order_data:
  postgres_payment_data:
  postgres_notification_data:

networks:
  user-db-net:
  product-db-net:
  order-db-net:
  payment-db-net:
  notification-db-net:
  redis-net:
  rabbitmq-net:
  elasticsearch-net:
  api-gateway-net:

